(define (expect msg actual expected)
  (define (display-error)
    (display "Actual: ")
    (display actual)
    (newline)
    (display "Expected: ")
    (display expected)
    (newline)
    (newline))
  (display msg)
  (newline)
  (if (equal? actual expected)
      (display "test passed")
      (display-error)))
